# Generated by Django 5.0.1 on 2024-01-19 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_events_alter_news_options_alter_news_news_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
