# Generated by Django 5.0.1 on 2024-01-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('anons', models.CharField(max_length=250, verbose_name='anons')),
                ('full_text', models.TextField(verbose_name='statya')),
                ('date', models.DateTimeField(verbose_name='date of publication')),
            ],
        ),
    ]
